#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

/* 主要定义了wendor路径 */
require(__DIR__ . '/common/config/common.php');

require(VENDOR . '/autoload.php');
require(VENDOR . '/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

if(file_exists(__DIR__ . '/common/config/main-local.php'))
{
	$config = yii\helpers\ArrayHelper::merge(
		require(__DIR__ . '/common/config/main.php'),
		require(__DIR__ . '/common/config/main-local.php'),
		require(__DIR__ . '/console/config/main.php'),
		require(__DIR__ . '/console/config/main-local.php')
	);
} else {
	$config = yii\helpers\ArrayHelper::merge(
		require(__DIR__ . '/common/config/main.php'),
		require(__DIR__ . '/console/config/main.php')
	);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
